### ISSUE TITLE
TODO List in Engine

### ISSUE THREAD

**Issue by MatheusMarchetti** [MatheusMarchetti/nino#2]
Rendering workflow:
- [x] Add Vertex Buffer wrapper
- [x] Add Index Buffer wrapper
- [x] Add shader wrapper
- [x] Add shader cache
- [x] Add pipeline state wrapper
- [x] Add input polling
- [x] Add random number generator
- [x] Add asset manager
- [x] Add UUID
- [x] Add asset cache
- [x] Add texture loading
- [x] Add texture cache
- [x] Add mipmapping and LOD/Quality settings
- [x] Add anisotopy settings
- [x] Add Material System
- [x] Add Camera System
- [ ] Add 2D primitives and batching
- [ ] Add assimp
- [ ] Add 3D primitives and instancing
- [ ] Add complex models
- [ ] Add compute pipeline
- [ ] Add environment mapping
- [ ] Add Image-based lighting
- [ ] Add Phong lighting pipeline to Material system
- [ ] Add Physically based rendering pipeline to Material system

Editor toolset:

- [ ] Add Entity concept
- [ ] Add Scene and Scene graphs
- [ ] Add Components
- [ ] Create Viewport Panel
- [ ] Create Scene Hierarchy Panel
- [ ] Create Entity Properties Panel
- [ ] Create Content Browser Panel
- [ ] Create Environment Inspector
- [ ] Create Materials Inspector
- [ ] Create Editor Camera
- [ ] Add mouse picking
- [ ] Add ImGuizmo
- [ ] Add scene serialization/deserialization
- [ ] Add shortcuts

**Comment by MatheusMarchetti** [comment]
Editor toolset:

- [ ] Add Entity concept
- [ ] Add Scene and Scene graphs
- [ ] Add Components
- [ ] Create Viewport Panel
- [ ] Create Scene Hierarchy Panel
- [ ] Create Entity Properties Panel
- [ ] Create Content Browser Panel
- [ ] Create Editor Camera
- [ ] Add mouse picking
- [ ] Add ImGuizmo
- [ ] Add scene serialization/deserialization
- [ ] Add shortcuts
